### PR TITLE
Update for CB 4.5

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Updated to show off Couchbase server 4.5 features and provide a consistent web service interface with a consistent Angular2 UI (source from).

Displays a mixture of:
- KV operations
- N1QL query
- LINQ2Couchbase usage
- Full Text Search

NOTE: There are some dependant bug fixes due for release in 2.3.9 for FTS support. I have tested them locally with the fixes and all worked fine.

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
@jeffrymorris @ingenthr Would be good to have someone to look over what I've done ASAP in case there are any changes required before Connect next week.

**Comment by jeffrymorris** [comment]
In progress.

**Comment by MikeGoldsmith** [comment]
Unfortunately I've found an [issue](https://github.com/couchbaselabs/Linq2Couchbase/issues/169) in the Linq2Couchbase update which prevents it from using 2.3.9.

We can either wait for that to be fixed or update the code sample to not use Linq2Couchbase.

@1tylermitchell @jeffrymorris @ingenthr

**Comment by MikeGoldsmith** [comment]
Just as a follow regarding the issue with Linq2Couchbase, the problem lies with the 2.3.9 release because it has not been signed correctly. This will be corrected in 2.3.10, which is scheduled for release on 6th December 2016.

**Comment by MikeGoldsmith** [comment]
With the new 2.3.10 release, this should be ready to merge again.

The Documentation that supports this update is in progress.

**Pull request merged**
